# Generated by Django 5.1.2 on 2026-02-25 22:04

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[800, 1000], upload_to='variants/extra/'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variant_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[800, 1000], upload_to='variants/'),
        ),
    ]
