# Generated by Django 5.1.2 on 2026-02-26 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_name', models.CharField(max_length=255, verbose_name='اسم المواصفة (مثال: الألوان)')),
                ('spec_value', models.CharField(max_length=255, verbose_name='القيمة (مثال: أحمر، أزرق)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='store.product')),
            ],
        ),
    ]
