# Generated by Django 5.1.2 on 2026-02-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productspecification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecification',
            name='spec_value',
            field=models.TextField(verbose_name='القيم (يمكنك إدخال أكثر من قيمة مفصولة بفاصلة)'),
        ),
    ]
