# Generated by Django 5.1.2 on 2026-03-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_productspecification_spec_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price for this size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base Price'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='spec_name',
            field=models.CharField(max_length=255, verbose_name='اسم المواصفة'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='spec_value',
            field=models.TextField(verbose_name='القيم'),
        ),
    ]
