# Generated by Django 5.1.2 on 2026-03-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_productsize_price_alter_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='price',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='spec_name',
            field=models.CharField(max_length=255, verbose_name='اسم المواصفة (مثال: الألوان)'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='spec_value',
            field=models.TextField(verbose_name='القيم (يمكنك إدخال أكثر من قيمة مفصولة بفاصلة)'),
        ),
    ]
